// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf Java Version: 4.27.1

package cn.pan.esdeathcli.proto;

/**
 * <pre>
 * 新增延迟消息响应
 * </pre>
 *
 * Protobuf type {@code esdeath.AddDelayMsgResult}
 */
public final class AddDelayMsgResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:esdeath.AddDelayMsgResult)
    AddDelayMsgResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      AddDelayMsgResult.class.getName());
  }
  // Use AddDelayMsgResult.newBuilder() to construct.
  private AddDelayMsgResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AddDelayMsgResult() {
    msgId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EsdeathProto.internal_static_esdeath_AddDelayMsgResult_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EsdeathProto.internal_static_esdeath_AddDelayMsgResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AddDelayMsgResult.class, Builder.class);
  }

  private int bitField0_;
  public static final int BASERESULT_FIELD_NUMBER = 1;
  private BaseResult baseResult_;
  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   * @return Whether the baseResult field is set.
   */
  @Override
  public boolean hasBaseResult() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   * @return The baseResult.
   */
  @Override
  public BaseResult getBaseResult() {
    return baseResult_ == null ? BaseResult.getDefaultInstance() : baseResult_;
  }
  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   */
  @Override
  public BaseResultOrBuilder getBaseResultOrBuilder() {
    return baseResult_ == null ? BaseResult.getDefaultInstance() : baseResult_;
  }

  public static final int MSGID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object msgId_ = "";
  /**
   * <code>string msgId = 2;</code>
   * @return The msgId.
   */
  @Override
  public String getMsgId() {
    Object ref = msgId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      msgId_ = s;
      return s;
    }
  }
  /**
   * <code>string msgId = 2;</code>
   * @return The bytes for msgId.
   */
  @Override
  public com.google.protobuf.ByteString
      getMsgIdBytes() {
    Object ref = msgId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      msgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseResult());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msgId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, msgId_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResult());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msgId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, msgId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AddDelayMsgResult)) {
      return super.equals(obj);
    }
    AddDelayMsgResult other = (AddDelayMsgResult) obj;

    if (hasBaseResult() != other.hasBaseResult()) return false;
    if (hasBaseResult()) {
      if (!getBaseResult()
          .equals(other.getBaseResult())) return false;
    }
    if (!getMsgId()
        .equals(other.getMsgId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResult()) {
      hash = (37 * hash) + BASERESULT_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResult().hashCode();
    }
    hash = (37 * hash) + MSGID_FIELD_NUMBER;
    hash = (53 * hash) + getMsgId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AddDelayMsgResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddDelayMsgResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddDelayMsgResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddDelayMsgResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddDelayMsgResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AddDelayMsgResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AddDelayMsgResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static AddDelayMsgResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static AddDelayMsgResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static AddDelayMsgResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AddDelayMsgResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static AddDelayMsgResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AddDelayMsgResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 新增延迟消息响应
   * </pre>
   *
   * Protobuf type {@code esdeath.AddDelayMsgResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:esdeath.AddDelayMsgResult)
      AddDelayMsgResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EsdeathProto.internal_static_esdeath_AddDelayMsgResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EsdeathProto.internal_static_esdeath_AddDelayMsgResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddDelayMsgResult.class, Builder.class);
    }

    // Construct using cn.pan.esdeathcli.proto.AddDelayMsgResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getBaseResultFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResult_ = null;
      if (baseResultBuilder_ != null) {
        baseResultBuilder_.dispose();
        baseResultBuilder_ = null;
      }
      msgId_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EsdeathProto.internal_static_esdeath_AddDelayMsgResult_descriptor;
    }

    @Override
    public AddDelayMsgResult getDefaultInstanceForType() {
      return AddDelayMsgResult.getDefaultInstance();
    }

    @Override
    public AddDelayMsgResult build() {
      AddDelayMsgResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public AddDelayMsgResult buildPartial() {
      AddDelayMsgResult result = new AddDelayMsgResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(AddDelayMsgResult result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResult_ = baseResultBuilder_ == null
            ? baseResult_
            : baseResultBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.msgId_ = msgId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AddDelayMsgResult) {
        return mergeFrom((AddDelayMsgResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AddDelayMsgResult other) {
      if (other == AddDelayMsgResult.getDefaultInstance()) return this;
      if (other.hasBaseResult()) {
        mergeBaseResult(other.getBaseResult());
      }
      if (!other.getMsgId().isEmpty()) {
        msgId_ = other.msgId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              msgId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private BaseResult baseResult_;
    private com.google.protobuf.SingleFieldBuilder<
        BaseResult, BaseResult.Builder, BaseResultOrBuilder> baseResultBuilder_;
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     * @return Whether the baseResult field is set.
     */
    public boolean hasBaseResult() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     * @return The baseResult.
     */
    public BaseResult getBaseResult() {
      if (baseResultBuilder_ == null) {
        return baseResult_ == null ? BaseResult.getDefaultInstance() : baseResult_;
      } else {
        return baseResultBuilder_.getMessage();
      }
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public Builder setBaseResult(BaseResult value) {
      if (baseResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResult_ = value;
      } else {
        baseResultBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public Builder setBaseResult(
        BaseResult.Builder builderForValue) {
      if (baseResultBuilder_ == null) {
        baseResult_ = builderForValue.build();
      } else {
        baseResultBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public Builder mergeBaseResult(BaseResult value) {
      if (baseResultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResult_ != null &&
          baseResult_ != BaseResult.getDefaultInstance()) {
          getBaseResultBuilder().mergeFrom(value);
        } else {
          baseResult_ = value;
        }
      } else {
        baseResultBuilder_.mergeFrom(value);
      }
      if (baseResult_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public Builder clearBaseResult() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResult_ = null;
      if (baseResultBuilder_ != null) {
        baseResultBuilder_.dispose();
        baseResultBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public BaseResult.Builder getBaseResultBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public BaseResultOrBuilder getBaseResultOrBuilder() {
      if (baseResultBuilder_ != null) {
        return baseResultBuilder_.getMessageOrBuilder();
      } else {
        return baseResult_ == null ?
            BaseResult.getDefaultInstance() : baseResult_;
      }
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        BaseResult, BaseResult.Builder, BaseResultOrBuilder>
        getBaseResultFieldBuilder() {
      if (baseResultBuilder_ == null) {
        baseResultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            BaseResult, BaseResult.Builder, BaseResultOrBuilder>(
                getBaseResult(),
                getParentForChildren(),
                isClean());
        baseResult_ = null;
      }
      return baseResultBuilder_;
    }

    private Object msgId_ = "";
    /**
     * <code>string msgId = 2;</code>
     * @return The msgId.
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string msgId = 2;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgId = 2;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      msgId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string msgId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      msgId_ = getDefaultInstance().getMsgId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string msgId = 2;</code>
     * @param value The bytes for msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:esdeath.AddDelayMsgResult)
  }

  // @@protoc_insertion_point(class_scope:esdeath.AddDelayMsgResult)
  private static final AddDelayMsgResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AddDelayMsgResult();
  }

  public static AddDelayMsgResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddDelayMsgResult>
      PARSER = new com.google.protobuf.AbstractParser<AddDelayMsgResult>() {
    @Override
    public AddDelayMsgResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddDelayMsgResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AddDelayMsgResult> getParserForType() {
    return PARSER;
  }

  @Override
  public AddDelayMsgResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

