// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf Java Version: 4.27.1

package cn.pan.esdeathcli.proto;

public interface DelayMsgAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:esdeath.DelayMsgAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.esdeath.AckStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.esdeath.AckStatus status = 1;</code>
   * @return The status.
   */
  AckStatus getStatus();

  /**
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  String getTopic();
  /**
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string consumerGroup = 3;</code>
   * @return The consumerGroup.
   */
  String getConsumerGroup();
  /**
   * <code>string consumerGroup = 3;</code>
   * @return The bytes for consumerGroup.
   */
  com.google.protobuf.ByteString
      getConsumerGroupBytes();

  /**
   * <code>string msgId = 4;</code>
   * @return The msgId.
   */
  String getMsgId();
  /**
   * <code>string msgId = 4;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();
}
