// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf Java Version: 4.27.1

package cn.pan.esdeathcli.proto;

public interface DelayMsgPullOrBuilder extends
    // @@protoc_insertion_point(interface_extends:esdeath.DelayMsgPull)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string consumerGroup = 2;</code>
   * @return The consumerGroup.
   */
  String getConsumerGroup();
  /**
   * <code>string consumerGroup = 2;</code>
   * @return The bytes for consumerGroup.
   */
  com.google.protobuf.ByteString
      getConsumerGroupBytes();
}
