// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf Java Version: 4.27.1

package cn.pan.esdeathcli.proto;

public interface DelayMsgCancelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:esdeath.DelayMsgCancel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgId = 1;</code>
   * @return The msgId.
   */
  String getMsgId();
  /**
   * <code>string msgId = 1;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();
}
