// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf Java Version: 4.27.1

package cn.pan.esdeathcli.proto;

public final class EsdeathProto {
  private EsdeathProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      EsdeathProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_DelayMsgCancel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_DelayMsgCancel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_DelayMsgAdd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_DelayMsgAdd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_DelayMsgPull_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_DelayMsgPull_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_DelayMsgAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_DelayMsgAck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_BaseResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_BaseResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_AddDelayMsgResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_AddDelayMsgResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_PullDelayMsgResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_PullDelayMsgResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_CancelDelayMsgResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_CancelDelayMsgResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_AckDelayMsgResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_AckDelayMsgResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_esdeath_RoleResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_esdeath_RoleResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014client.proto\022\007esdeath\032\033google/protobuf" +
      "/empty.proto\"\037\n\016DelayMsgCancel\022\r\n\005msgId\030" +
      "\001 \001(\t\"\\\n\013DelayMsgAdd\022\021\n\tdelayTime\030\001 \001(\003\022" +
      "\r\n\005topic\030\002 \001(\t\022\013\n\003tag\030\003 \001(\t\022\r\n\005msgId\030\004 \001" +
      "(\t\022\017\n\007payload\030\005 \001(\t\"4\n\014DelayMsgPull\022\r\n\005t" +
      "opic\030\001 \001(\t\022\025\n\rconsumerGroup\030\002 \001(\t\"f\n\013Del" +
      "ayMsgAck\022\"\n\006status\030\001 \001(\0162\022.esdeath.AckSt" +
      "atus\022\r\n\005topic\030\002 \001(\t\022\025\n\rconsumerGroup\030\003 \001" +
      "(\t\022\r\n\005msgId\030\004 \001(\t\"A\n\nBaseResult\022%\n\006statu" +
      "s\030\001 \001(\0162\025.esdeath.ResultStatus\022\014\n\004desc\030\002" +
      " \001(\t\"K\n\021AddDelayMsgResult\022\'\n\nbaseResult\030" +
      "\001 \001(\0132\023.esdeath.BaseResult\022\r\n\005msgId\030\002 \001(" +
      "\t\"y\n\022PullDelayMsgResult\022\'\n\nbaseResult\030\001 " +
      "\001(\0132\023.esdeath.BaseResult\022\r\n\005topic\030\002 \001(\t\022" +
      "\013\n\003tag\030\003 \001(\t\022\r\n\005msgId\030\004 \001(\t\022\017\n\007payload\030\005" +
      " \001(\t\"?\n\024CancelDelayMsgResult\022\'\n\nbaseResu" +
      "lt\030\001 \001(\0132\023.esdeath.BaseResult\"<\n\021AckDela" +
      "yMsgResult\022\'\n\nbaseResult\030\001 \001(\0132\023.esdeath" +
      ".BaseResult\"R\n\nRoleResult\022\'\n\nbaseResult\030" +
      "\001 \001(\0132\023.esdeath.BaseResult\022\033\n\004role\030\002 \001(\016" +
      "2\r.esdeath.Role*#\n\tAckStatus\022\007\n\003ACK\020\000\022\r\n" +
      "\tRECONSUME\020\001*M\n\014ResultStatus\022\013\n\007SUCCESS\020" +
      "\000\022\010\n\004FAIL\020\001\022\026\n\022REFUSE_BY_FOLLOWER\020\002\022\016\n\nN" +
      "O_MESSAGE\020\003* \n\004Role\022\n\n\006LEADER\020\000\022\014\n\010FOLLO" +
      "WER\020\0012\321\002\n\007Esdeath\022?\n\013AddDelayMsg\022\024.esdea" +
      "th.DelayMsgAdd\032\032.esdeath.AddDelayMsgResu" +
      "lt\022B\n\014PullDelayMsg\022\025.esdeath.DelayMsgPul" +
      "l\032\033.esdeath.PullDelayMsgResult\022?\n\013AckDel" +
      "ayMsg\022\024.esdeath.DelayMsgAck\032\032.esdeath.Ac" +
      "kDelayMsgResult\022H\n\016CancelDelayMsg\022\027.esde" +
      "ath.DelayMsgCancel\032\035.esdeath.CancelDelay" +
      "MsgResult\0226\n\007GetRole\022\026.google.protobuf.E" +
      "mpty\032\023.esdeath.RoleResultB4\n\027cn.pan.esde" +
      "athcli.protoB\014EsdeathProtoH\001P\001\210\001\001\240\001\001\330\001\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_esdeath_DelayMsgCancel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_esdeath_DelayMsgCancel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_DelayMsgCancel_descriptor,
        new String[] { "MsgId", });
    internal_static_esdeath_DelayMsgAdd_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_esdeath_DelayMsgAdd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_DelayMsgAdd_descriptor,
        new String[] { "DelayTime", "Topic", "Tag", "MsgId", "Payload", });
    internal_static_esdeath_DelayMsgPull_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_esdeath_DelayMsgPull_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_DelayMsgPull_descriptor,
        new String[] { "Topic", "ConsumerGroup", });
    internal_static_esdeath_DelayMsgAck_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_esdeath_DelayMsgAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_DelayMsgAck_descriptor,
        new String[] { "Status", "Topic", "ConsumerGroup", "MsgId", });
    internal_static_esdeath_BaseResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_esdeath_BaseResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_BaseResult_descriptor,
        new String[] { "Status", "Desc", });
    internal_static_esdeath_AddDelayMsgResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_esdeath_AddDelayMsgResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_AddDelayMsgResult_descriptor,
        new String[] { "BaseResult", "MsgId", });
    internal_static_esdeath_PullDelayMsgResult_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_esdeath_PullDelayMsgResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_PullDelayMsgResult_descriptor,
        new String[] { "BaseResult", "Topic", "Tag", "MsgId", "Payload", });
    internal_static_esdeath_CancelDelayMsgResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_esdeath_CancelDelayMsgResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_CancelDelayMsgResult_descriptor,
        new String[] { "BaseResult", });
    internal_static_esdeath_AckDelayMsgResult_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_esdeath_AckDelayMsgResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_AckDelayMsgResult_descriptor,
        new String[] { "BaseResult", });
    internal_static_esdeath_RoleResult_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_esdeath_RoleResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_esdeath_RoleResult_descriptor,
        new String[] { "BaseResult", "Role", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
