// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf Java Version: 4.27.1

package cn.pan.esdeathcli.proto;

public interface PullDelayMsgResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:esdeath.PullDelayMsgResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   * @return Whether the baseResult field is set.
   */
  boolean hasBaseResult();
  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   * @return The baseResult.
   */
  BaseResult getBaseResult();
  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   */
  BaseResultOrBuilder getBaseResultOrBuilder();

  /**
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  String getTopic();
  /**
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string tag = 3;</code>
   * @return The tag.
   */
  String getTag();
  /**
   * <code>string tag = 3;</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>string msgId = 4;</code>
   * @return The msgId.
   */
  String getMsgId();
  /**
   * <code>string msgId = 4;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>string payload = 5;</code>
   * @return The payload.
   */
  String getPayload();
  /**
   * <code>string payload = 5;</code>
   * @return The bytes for payload.
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
}
