// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf Java Version: 4.27.1

package cn.pan.esdeathcli.proto;

/**
 * Protobuf enum {@code esdeath.ResultStatus}
 */
public enum ResultStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUCCESS = 0;</code>
   */
  SUCCESS(0),
  /**
   * <code>FAIL = 1;</code>
   */
  FAIL(1),
  /**
   * <code>REFUSE_BY_FOLLOWER = 2;</code>
   */
  REFUSE_BY_FOLLOWER(2),
  /**
   * <code>NO_MESSAGE = 3;</code>
   */
  NO_MESSAGE(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      ResultStatus.class.getName());
  }
  /**
   * <code>SUCCESS = 0;</code>
   */
  public static final int SUCCESS_VALUE = 0;
  /**
   * <code>FAIL = 1;</code>
   */
  public static final int FAIL_VALUE = 1;
  /**
   * <code>REFUSE_BY_FOLLOWER = 2;</code>
   */
  public static final int REFUSE_BY_FOLLOWER_VALUE = 2;
  /**
   * <code>NO_MESSAGE = 3;</code>
   */
  public static final int NO_MESSAGE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ResultStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ResultStatus forNumber(int value) {
    switch (value) {
      case 0: return SUCCESS;
      case 1: return FAIL;
      case 2: return REFUSE_BY_FOLLOWER;
      case 3: return NO_MESSAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ResultStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ResultStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ResultStatus>() {
          public ResultStatus findValueByNumber(int number) {
            return ResultStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return EsdeathProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final ResultStatus[] VALUES = values();

  public static ResultStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ResultStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:esdeath.ResultStatus)
}

