// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client.proto
// Protobuf Java Version: 4.27.1

package cn.pan.esdeathcli.proto;

/**
 * Protobuf type {@code esdeath.RoleResult}
 */
public final class RoleResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:esdeath.RoleResult)
    RoleResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      RoleResult.class.getName());
  }
  // Use RoleResult.newBuilder() to construct.
  private RoleResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RoleResult() {
    role_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EsdeathProto.internal_static_esdeath_RoleResult_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EsdeathProto.internal_static_esdeath_RoleResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RoleResult.class, Builder.class);
  }

  private int bitField0_;
  public static final int BASERESULT_FIELD_NUMBER = 1;
  private BaseResult baseResult_;
  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   * @return Whether the baseResult field is set.
   */
  @Override
  public boolean hasBaseResult() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   * @return The baseResult.
   */
  @Override
  public BaseResult getBaseResult() {
    return baseResult_ == null ? BaseResult.getDefaultInstance() : baseResult_;
  }
  /**
   * <code>.esdeath.BaseResult baseResult = 1;</code>
   */
  @Override
  public BaseResultOrBuilder getBaseResultOrBuilder() {
    return baseResult_ == null ? BaseResult.getDefaultInstance() : baseResult_;
  }

  public static final int ROLE_FIELD_NUMBER = 2;
  private int role_ = 0;
  /**
   * <code>.esdeath.Role role = 2;</code>
   * @return The enum numeric value on the wire for role.
   */
  @Override public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.esdeath.Role role = 2;</code>
   * @return The role.
   */
  @Override public Role getRole() {
    Role result = Role.forNumber(role_);
    return result == null ? Role.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseResult());
    }
    if (role_ != Role.LEADER.getNumber()) {
      output.writeEnum(2, role_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResult());
    }
    if (role_ != Role.LEADER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, role_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RoleResult)) {
      return super.equals(obj);
    }
    RoleResult other = (RoleResult) obj;

    if (hasBaseResult() != other.hasBaseResult()) return false;
    if (hasBaseResult()) {
      if (!getBaseResult()
          .equals(other.getBaseResult())) return false;
    }
    if (role_ != other.role_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResult()) {
      hash = (37 * hash) + BASERESULT_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResult().hashCode();
    }
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + role_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RoleResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoleResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoleResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoleResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoleResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RoleResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RoleResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static RoleResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static RoleResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static RoleResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RoleResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static RoleResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RoleResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code esdeath.RoleResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:esdeath.RoleResult)
      RoleResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EsdeathProto.internal_static_esdeath_RoleResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EsdeathProto.internal_static_esdeath_RoleResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoleResult.class, Builder.class);
    }

    // Construct using cn.pan.esdeathcli.proto.RoleResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getBaseResultFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResult_ = null;
      if (baseResultBuilder_ != null) {
        baseResultBuilder_.dispose();
        baseResultBuilder_ = null;
      }
      role_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EsdeathProto.internal_static_esdeath_RoleResult_descriptor;
    }

    @Override
    public RoleResult getDefaultInstanceForType() {
      return RoleResult.getDefaultInstance();
    }

    @Override
    public RoleResult build() {
      RoleResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RoleResult buildPartial() {
      RoleResult result = new RoleResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(RoleResult result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResult_ = baseResultBuilder_ == null
            ? baseResult_
            : baseResultBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.role_ = role_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RoleResult) {
        return mergeFrom((RoleResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RoleResult other) {
      if (other == RoleResult.getDefaultInstance()) return this;
      if (other.hasBaseResult()) {
        mergeBaseResult(other.getBaseResult());
      }
      if (other.role_ != 0) {
        setRoleValue(other.getRoleValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              role_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private BaseResult baseResult_;
    private com.google.protobuf.SingleFieldBuilder<
        BaseResult, BaseResult.Builder, BaseResultOrBuilder> baseResultBuilder_;
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     * @return Whether the baseResult field is set.
     */
    public boolean hasBaseResult() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     * @return The baseResult.
     */
    public BaseResult getBaseResult() {
      if (baseResultBuilder_ == null) {
        return baseResult_ == null ? BaseResult.getDefaultInstance() : baseResult_;
      } else {
        return baseResultBuilder_.getMessage();
      }
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public Builder setBaseResult(BaseResult value) {
      if (baseResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResult_ = value;
      } else {
        baseResultBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public Builder setBaseResult(
        BaseResult.Builder builderForValue) {
      if (baseResultBuilder_ == null) {
        baseResult_ = builderForValue.build();
      } else {
        baseResultBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public Builder mergeBaseResult(BaseResult value) {
      if (baseResultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResult_ != null &&
          baseResult_ != BaseResult.getDefaultInstance()) {
          getBaseResultBuilder().mergeFrom(value);
        } else {
          baseResult_ = value;
        }
      } else {
        baseResultBuilder_.mergeFrom(value);
      }
      if (baseResult_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public Builder clearBaseResult() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResult_ = null;
      if (baseResultBuilder_ != null) {
        baseResultBuilder_.dispose();
        baseResultBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public BaseResult.Builder getBaseResultBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    public BaseResultOrBuilder getBaseResultOrBuilder() {
      if (baseResultBuilder_ != null) {
        return baseResultBuilder_.getMessageOrBuilder();
      } else {
        return baseResult_ == null ?
            BaseResult.getDefaultInstance() : baseResult_;
      }
    }
    /**
     * <code>.esdeath.BaseResult baseResult = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        BaseResult, BaseResult.Builder, BaseResultOrBuilder>
        getBaseResultFieldBuilder() {
      if (baseResultBuilder_ == null) {
        baseResultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            BaseResult, BaseResult.Builder, BaseResultOrBuilder>(
                getBaseResult(),
                getParentForChildren(),
                isClean());
        baseResult_ = null;
      }
      return baseResultBuilder_;
    }

    private int role_ = 0;
    /**
     * <code>.esdeath.Role role = 2;</code>
     * @return The enum numeric value on the wire for role.
     */
    @Override public int getRoleValue() {
      return role_;
    }
    /**
     * <code>.esdeath.Role role = 2;</code>
     * @param value The enum numeric value on the wire for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleValue(int value) {
      role_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.esdeath.Role role = 2;</code>
     * @return The role.
     */
    @Override
    public Role getRole() {
      Role result = Role.forNumber(role_);
      return result == null ? Role.UNRECOGNIZED : result;
    }
    /**
     * <code>.esdeath.Role role = 2;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(Role value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      role_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.esdeath.Role role = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      bitField0_ = (bitField0_ & ~0x00000002);
      role_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:esdeath.RoleResult)
  }

  // @@protoc_insertion_point(class_scope:esdeath.RoleResult)
  private static final RoleResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RoleResult();
  }

  public static RoleResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoleResult>
      PARSER = new com.google.protobuf.AbstractParser<RoleResult>() {
    @Override
    public RoleResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RoleResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RoleResult> getParserForType() {
    return PARSER;
  }

  @Override
  public RoleResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

